name = "short-urls"
workers_dev = false
route = "pydis.com/*"
main = "src/index.ts"
kv_namespaces = [
	 { binding = "urls", id = "c6d38750203b40e89579731430d22429" }
]
compatibility_date = "2022-08-22"
