name = "github-filter-worker"
type = "webpack"
account_id = "502aea548379e08369697540cc0bb0d1"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
  { binding = "EMOJIS", id = "183f1ae82b8d458f983e39eb2c99fa9a", preview_id = "183f1ae82b8d458f983e39eb2c99fa9a" }
]
